### ISSUE TITLE
TypeError: string indices must be integers

### ISSUE THREAD

**Issue by ikke-t** [Dis90/plugin.video.katsomo#2]
Kodi cannot play video:

```
2020-04-24 23:12:32.087 T:2743783632   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.TypeError'>
                                            Error Contents: string indices must be integers
                                            Traceback (most recent call last):
                                              File "/home/pi/.kodi/addons/plugin.video.katsomo/addon.py", line 205, in <module>
                                                router(sys.argv[2][1:])
                                              File "/home/pi/.kodi/addons/plugin.video.katsomo/addon.py", line 188, in router
                                                helper.play_item(params['video_id'])
                                              File "/home/pi/.kodi/addons/plugin.video.katsomo/resources/lib/kodihelper.py", line 137, in play_item
                                                stream = self.k.get_stream(video_id)
                                              File "/home/pi/.kodi/addons/plugin.video.katsomo/resources/lib/katsomo.py", line 165, in get_stream
                                                if isinstance(data_dict['items']['item'], list):
                                            TypeError: string indices must be integers
                                            -->End of Python script error report<--
2020-04-24 23:12:32.287 T:2972765280   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.katsomo/?action=play&video_id=1233703]
```

host os:  raspbian - /etc/debian_version 10.3
kodi: 2:18.6-1~buster
inputstream adaptive: latest from git
Raspi4

**Comment by ikke-t** [comment]
Turns out this is a special case. It seems Katsomo lists the latest episode of the series some days before it's really watchable. Perhaps they sell that episode early access to paying customers or something.

Anyhow, this happens with such episode title, the older ones do work fine.
